### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by vanmil** [mnshankar/oc-cacheroute-plugin#5]
After installing this plugin we get the error `Serialization of 'Closure' is not allowed` on `/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php line 65`. I am on OctoberCMS version 431.

**Comment by mnshankar** [comment]
Thank you!

**Comment by vanmil** [comment]
Thank you for the fast fix!
